version: '3.7'
services:
  # MongoDB
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge