// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/cristovaoolegario/aluraflix-api/db"
	"github.com/cristovaoolegario/aluraflix-api/router"
)

// Injectors from wire.go:

func InitApp() App {
	databaseService := db.ProvideDatabaseService()
	categoryService := db.ProvideCategoryService(databaseService)
	videoService := db.ProvideVideoService(categoryService, databaseService)
	videoRouter := router.ProvideVideoRouter(videoService)
	categoryRouter := router.ProvideCategoryRouter(categoryService)
	muxRouter := router.ProvideRouter(videoRouter, categoryRouter)
	app := ProvideApp(muxRouter, databaseService)
	return app
}
