name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: cristovaoolegario/aluraflix-api
          tags: latest, ${{ github.run_number }}
